google:
  books:
    url: ${GOOGLE_URL}
    key: ${GOOGLE_KEY}

spring:
  datasource:
    url: ${DATABASE_URL}

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: ${JDBC_CLOB:false}

cors:
  address: ${CORS_URL}