google:
  books:
    url: ${GOOGLE_URL}
    key: ${GOOGLE_KEY}
  secret:
    key:
      path: ${SECRET_KEY_PATH}
  oauth:
    callback:
      uri: ${CALLBACK_OAUTH_URI}
  credentials:
    folder:
      path: ${CREDENTIAL_PATH}

spring:
  datasource:
    url: ${DATABASE_URL}
  servlet:
    multipart:
      location: ${TEMP_FILE_LOCATION:${java.io.tmpdir}}
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: ${JDBC_CLOB:false}
        order_by:
          default_null_ordering: last
  liquibase:
    enabled: false
cors:
  address: ${CORS_URL}